CREATE DATABASE GEMAS;
USE GEMAS;

CREATE TABLE USUARIO_GEMAS(
	EMAIL VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    CODIGO VARCHAR(1)
);

SELECT * FROM USUARIO_GEMAS;
DROP TABLE USUARIO_GEMAS;

